#!/usr/bin/python

address = 0
default = 0xF

def outNybble(x):
    global address
    global default
    if (address >= 2):
        x = ~x & 0xF
    if (x != default):
        print "'h%02x: dout <= 4'h%x;" % (address, x & 0x0F)
    address+=1
    
def outByte(x):
    outNybble(x >> 4)
    outNybble(x & 0x0F)

def outShort(x):
    outByte(x >> 8)
    outByte(x & 0xFF)

def outLong(x):
    outShort(x >> 16)
    outShort(x & 0xFFFF)
    
rom = "0xE6 0x51 0x80 0x00 0x07 0xDB 0x00 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x00 0x00"

memavailable = 0x20
versions = {"Z2": 0xC0, "Z3": 0x80}
sizes = {"64K": 0x01, "128K": 0x02, "256K": 0x03, "512K": 0x04, "1M": 0x05, "2M": 0x06, "4M": 0x07, "8M": 0x00}


eType = versions["Z2"] | sizes["2M"] | memavailable
eProduct = 0x88
eFlags = 0x80
eManuID = 2011
eSerial = 12345
eRomVector = 0
print "case (zaddr)"
outByte(eType)
outByte(eProduct)
outByte(eFlags)
outByte(0x00) #reserved
outShort(eManuID)
outLong(eSerial)
outShort(eRomVector)
outLong(0x00) #reserved
print "default: dout <= 4'h%x;" % (default)
print "endcase"
